### ISSUE TITLE
Cannot authenticate on MacOS

### ISSUE THREAD

**Issue by Apaipengpo** [0xf4b1/traktor-streaming-proxy#16]
Hi,
I have the same issue than #13 but on MacOS. I tried the certificate thing but it did not work. I get always this message in traktor:
![image](https://github.com/0xf4b1/traktor-streaming-proxy/assets/159691114/39694434-1865-4a96-9928-27ef22c5aea6)

and in the docker logs is also only these two requests:
`traktor-streaming-proxy-traktor-1  | 392767 [eventLoopGroupProxy-4-13] INFO ktor.application  - 302 Found: GET - /v4/auth/o/authorize/ in 0ms -> traktor://bp_oauth?code=foo
traktor-streaming-proxy-traktor-1  | 397384 [eventLoopGroupProxy-4-14] INFO ktor.application  - 200 OK: GET - /v4/auth/logout/ in 0ms`

I also tried the various license file with no luck.

What can I do?

**Comment by 0xf4b1** [comment]
Hey, it seems it fails with the first request and this is before the license part. Most likely the system does not trust the SSL certificate, have you added the CA certificate to the system trust store and verified it works with the curl command in step 5?

**Comment by Simacrus** [comment]
have same issue, tested with `curl https://api.beatport.com/v4/catalog/genres/` and get `    "results": [
        {
            "id": 1,
            "name": "YouTube"
        }
    ]` 
    added certificates to trust store 
![Снимок экрана 2024-02-18 в 22 55 48](https://github.com/0xf4b1/traktor-streaming-proxy/assets/99753312/f3d688ac-5954-41c7-8fcb-6ef5376c94f2) 

console log:
![Снимок экрана 2024-02-18 в 22 57 50](https://github.com/0xf4b1/traktor-streaming-proxy/assets/99753312/a50024fb-0c11-44bf-8e2e-b145583b5385)


but still have this notification

**Comment by 0xf4b1** [comment]
I assume you are using a more recent version of Traktor, so it's most likely the same issue as #17 which should be working again with the updated instructions in the README
