### ISSUE TITLE
Spotify broke

### ISSUE THREAD

**Issue by deluxeGitHub** [0xf4b1/traktor-streaming-proxy#19]
Hi @0xf4b1 ,
I hope you can come to the rescue once more. The Spotify connection seems to be broken again.
Greetz Sam

**Comment by 0xf4b1** [comment]
Hey, this time it's an authorization issue in the spotify library https://github.com/librespot-org/librespot-java/issues/921 :/ I t's a known problem for me as I have it also in my android app https://github.com/soundcrowd/soundcrowd-plugin-spotify/issues/2 where I also miss the spotify functionality. When I find some more time, I'll try to resolve it or find a workaround for both
